"""add knockout fields to matches

Revision ID: c1a5235bfac0
Revises: d06a552bc994
Create Date: 2026-09-25 11:06:26.216356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a5235bfac0'
down_revision: Union[str, Sequence[str], None] = 'd06a552bc994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('round', sa.String(length=20), nullable=True))
    op.add_column('matches', sa.Column('bracket_slot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'bracket_slot')
    op.drop_column('matches', 'round')
    # ### end Alembic commands ###
